import Layout from '@layouts/Layout'
import Head from 'next/head'
import { data } from 'utils/fakeData';
import _ from 'lodash';
import { DataMaterials } from '@components/DataMaterials';
import { ActionButtonM } from '@components/ActionButtonM';
import { ModalEntradas } from '@components/modals/ModalEntradas';
import { ModalSalidas } from '@components/modals/ModalSalidas';
import { MovimientosContextProvider } from '@context/MovimientosContext';

export default function Home() {
  return (
    <Layout>
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <MovimientosContextProvider>
          <>
            <TableDesktop/>
            <MobileCards/>
          </>
        </MovimientosContextProvider>

      </>
    </Layout>
  )
}
const TableDesktop = () => {
  const tableData = data;
  return (
    <div className='hidden md:flex flex-col p-10 w-full h-full gap-3'>
      <div className='flex w-full justify-center'>
        <h1 >Gestión de inventario</h1>
      </div>
      <div className='flex justify-between'>
        <DataMaterials/>
        <ActionButtonM/> 
      </div>
      <div className='flex h-full w-full justify-center'>
        <table>
          <thead>
            <tr>
              <th>Identificador</th>
              <th>Fecha</th>
              <th>Entrada</th>
              <th>Salida</th>
            </tr>
          </thead>
          <tbody>
            {tableData.map((el)=>{
              return(
                <tr>
                  <td>{el.Identificador}</td>
                  <td>{el.Fecha}</td>
                  <td>{el.Entrada}</td>
                  <td>{el.Salida}</td>
                </tr>
              );
            }) }
          </tbody>
        </table>  
      </div>
      <div className='flex justify-end'>saldo</div>
      <ModalEntradas/>
      <ModalSalidas/>
    </div>  
  );
};
const MobileCards = () => {
  return (
    <div className='flex flex-col p-4 h-full w-full md:hidden'>
    <div className='flex w-full justify-center'>
      <h1 >Gestión de inventario</h1>
    </div>
    <div className='flex justify-end'>
      <DataMaterials/>
      <ActionButtonM/>
    </div>
    <div className='grid grid-cols-2 h-full'>
      <div>Card Entrada</div>
      <div>Card Salida</div>
      <div>Card Entrada</div>
      <div>Card Salida</div>
      <div>Card Entrada</div>
      <div>Card Salida</div>
    </div>
    <div className='flex justify-end'>saldo</div>
  </div>
  )
};
