import Layout from '@layouts/Layout'
import Head from 'next/head'


export default function Home() {
  return (
    <Layout>
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='flex flex-col p-10 w-full h-full'>
          <div className='flex w-full justify-center'>
            <h1 className='h1'>Gestión de inventario</h1>
          </div>
          <div className='flex justify-between'>
            <div>Material 1</div>
            <div>Agregar movimiento</div>
          </div>
          <div className='h-full w-full'>tabla</div>
          <div>saldo</div>
        </div>
      </>
    </Layout>
  )
}
